name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install all other dependencies

    - name: Install pytest
      run: |
        pip install pytest  # Install pytest directly

    - name: Run tests
      run: |
        pytest  # Run your tests
