name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Your requirements file

    - name: Run tests
      run: |
        # Replace with your test command
        pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        # Commands to deploy your app
        # Example: 
        # ssh user@your-server "cd /path/to/your/app && git pull && systemctl restart your-app-service"
